name: "jira-set-version-action"

description: "Action for work with Jira"

branding:
  icon: git-pull-request
  color: green

inputs:
  action:
    required: true
    description: "Action id"
  project:
    required: false
    description: "Alias of Project"
  version:
    required: false
    description: "Version of release"
  issues:
    required: false
    description: "Set of issues"
  new-name:
    required: false
    description: "New name for version"
  branch-name:
    required: false
    description: "Name of branch"

runs:
  using: "node16"
  main: "./dist/index.js"
